stages:
  - build
  - publish
  - deploy

variables:
  VERSION: $CI_COMMIT_SHORT_SHA
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: golang:latest
  script:
    GOOS=linux go build .
  artifacts:
    paths:
      - idcardgenerator
    expire_in: 1 week
  only:
    - master

publish:
  stage: publish
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.3.4
  script:
    - helm upgrade -i --set imageVersion=$VERSION idcard-processor chart
  environment:
    name: production
    url: https://gphrase.de/perso
  only:
    - master
