stages:
  - build
  - publish

variables:
  IMAGE_TAG: $CI_REGISTRY:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: golang:latest
  script:
    GOOS=linux go build .
  artifacts:
    paths:
      - idcardgenerator
    expire_in: 1 week
  only:
    - master

publish:
  stage: publish
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
