apiVersion: apps/v1
kind: Deployment
metadata:
  name: idcardgenerator
  labels:
    app: idcardgenerator
spec:
  selector:
    matchLabels:
      app: idcardgenerator
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  template:
    metadata:
      name: idcardgenerator
      labels:
        app: idcardgenerator
    spec:
      containers:
        - name: idcardgenerator
          image: "registry.gitlab.com/pscheid92/idcardgenerator:{{ required "Set valid .Values.imageVersion entry!" .Values.imageVersion }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
