{{ if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: idcardgenerator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: idcardgenerator
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
{{ end }}
