apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idcardgenerator
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    cert-manager.io/cluster-issuer: letsencrypt

spec:
  tls:
    - hosts:
        - gphrase.de
      secretName: gphrase-cert-secret
  rules:
    - host: gphrase.de
      http:
        paths:
          - path: /perso
            pathType: Prefix
            backend:
                service:
                    name: idcardgenerator
                    port:
                        number: 8080
