apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idcardgenerator
  annotations:
    cert-manager.io/issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  tls:
    - hosts:
        - gphrase.de
      secretName: letsencrypt-tls

  rules:
    - host: gphrase.de
      http:
        paths:
          - path: /perso
            pathType: Prefix
            backend:
              service:
                name: idcardgenerator
                port:
                  number: 8080
