name: Continious Integration Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'

      - name: Checkout project code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v .

      - name: Build and publish image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: pscheid92/idcard-generator/idcard-generator
          tags: ${{ github.sha }}

  deploy:
    name: Deploy to kubernetes cluster
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: >-
            helm upgrade
            --install
            --namespace idcard-generator
            --set imageVersion=${{ github.sha }}
            --values ./chart/production.yaml
            idcard-generator
            ./chart
